/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cli;

import org.junit.Ignore;
import org.junit.jupiter.api.Test;

class AppTest {
  @Ignore
  @Test
  void appHasAGreeting() throws InterruptedException {

  }
}
